package PulsaElektronix;

import java.awt.*;
/**
 * @author Wiguna Ramadhan
 * @kelas X - RPL 2
 * @sekolah SMKN 1 CIBINONG
 */
public class PE_aboutMe extends javax.swing.JFrame {

    /**
     * Creates new form PKL_credit
     */
    public PE_aboutMe() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto = new javax.swing.JLabel();
        about_me = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        tanggal_lahir = new javax.swing.JLabel();
        nama_sekolah = new javax.swing.JLabel();
        teknik_jurusan = new javax.swing.JLabel();
        nomor_telepon = new javax.swing.JLabel();
        facebook = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pulsa Elektronix || About Me");
        setResizable(false);

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/profil.jpg"))); // NOI18N

        about_me.setBackground(new java.awt.Color(0, 102, 255));
        about_me.setFont(new java.awt.Font("Tele-Marines", 0, 18)); // NOI18N
        about_me.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about_me.setText("About Me");

        nama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama.setText("Wiguna Ramadhan");

        tanggal_lahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanggal_lahir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggal_lahir.setText("Bogor, 20 Desember 1998");

        nama_sekolah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama_sekolah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama_sekolah.setText("SMKN 1 CIBINONG");

        teknik_jurusan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teknik_jurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teknik_jurusan.setText("REKAYASA PERANGKAT LUNAK");

        nomor_telepon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomor_telepon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/phone.png"))); // NOI18N
        nomor_telepon.setText("+62 857 - 7323 - 3588");

        facebook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/facebook.png"))); // NOI18N
        facebook.setText("facebook.com/wigunaramadhan");

        twitter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/twitter.png"))); // NOI18N
        twitter.setText("@WigunapPoconggg");

        button_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/back.png"))); // NOI18N
        button_back.setText("BACK");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(about_me, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nama_sekolah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggal_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomor_telepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teknik_jurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(facebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_back)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(about_me, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggal_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(nama_sekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teknik_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomor_telepon)
                        .addGap(3, 3, 3)
                        .addComponent(facebook, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twitter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
            new PE_login().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_button_backActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about_me;
    private javax.swing.JButton button_back;
    private javax.swing.JLabel facebook;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama_sekolah;
    private javax.swing.JLabel nomor_telepon;
    private javax.swing.JLabel tanggal_lahir;
    private javax.swing.JLabel teknik_jurusan;
    private javax.swing.JLabel twitter;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
   }
}
