package PulsaElektronix;
/**
 * @author Wiguna Ramadhan
 * @kelas X - RPL 2
 * @sekolah SMKN 1 CIBINONG
 */
import java.awt.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class PE_dataPengiriman extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public static LinkedList<PE_data> link = new LinkedList<PE_data>();
    Iterator<PE_data> itr = link.iterator();
    
    String provider, jumlah, harga;
    
    int i = 0;
    int saldo = 0;
    
    public void add(String provider, String jumlah, String harga){
        link.add (new PE_data (provider, jumlah, harga));
    }
    
    void data() {
        form_harga.setText(link.get(i).getharga());
    }
    
    public PE_dataPengiriman() {
        initComponents();
        setIcon();
        conn = MySQLConnection.ConnectDb();
        update_table();
        link.add(new PE_data("Telkomsel", "Rp 5000", "Rp 6500"));
        link.add(new PE_data("Telkomsel", "Rp 10.000", "Rp 12.000"));
        link.add(new PE_data("Telkomsel", "Rp 25.000", "Rp 27.000"));
        link.add(new PE_data("Telkomsel", "Rp 50.000", "Rp 52.000"));
        link.add(new PE_data("Telkomsel", "Rp 100.000", "Rp 102.000"));
        link.add(new PE_data("Indosat", "Rp 5000", "Rp 6500"));
        link.add(new PE_data("Indosat", "Rp 10.000", "Rp 11.500"));
        link.add(new PE_data("Indosat", "Rp 25.000", "Rp 26.500"));
        link.add(new PE_data("Indosat", "Rp 50.000", "Rp 51.500"));
        link.add(new PE_data("Indosat", "Rp 100.000", "Rp 101.500"));
        link.add(new PE_data("XL", "Rp 5000", "Rp 6500"));
        link.add(new PE_data("XL", "Rp 10.000", "Rp 11.000"));
        link.add(new PE_data("XL", "Rp 25.000", "Rp 26.000"));
        link.add(new PE_data("XL", "Rp 50.000", "Rp 51.000"));
        link.add(new PE_data("XL", "Rp 100.000", "Rp 101.000"));
        link.add(new PE_data("Axis", "Rp 5000", "Rp 6500"));
        link.add(new PE_data("Axis", "Rp 10.000", "Rp 11.500"));
        link.add(new PE_data("Axis", "Rp 25.000", "Rp 26.000"));
        link.add(new PE_data("Axis", "Rp 50.000", "Rp 51.500"));
        link.add(new PE_data("Axis", "Rp 100.000", "Rp 102.500"));
        link.add(new PE_data("Smartfren", "Rp 5000", "Rp 6500"));
        link.add(new PE_data("Smartfren", "Rp 10.000", "Rp 11.000"));
        link.add(new PE_data("Smartfren", "Rp 25.000", "Rp 25.500"));
        link.add(new PE_data("Smartfren", "Rp 50.000", "Rp 51.000"));
        link.add(new PE_data("Smartfren", "Rp 100.000", "Rp 101.000"));
    }
    
    private void update_table(){
        try{
            String sql = "SELECT * from tbl_kirim";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            data_pengiriman.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_pengiriman_pulsa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_pengiriman = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        form_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        form_harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomor_tujuan = new javax.swing.JTextField();
        button_edit = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_insert = new javax.swing.JButton();
        ComboBox_provider = new javax.swing.JComboBox();
        jumlah_pulsa = new javax.swing.JComboBox();
        button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pulsa Elektronix || Data Pengiriman");
        setResizable(false);

        data_pengiriman_pulsa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        data_pengiriman_pulsa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        data_pengiriman_pulsa.setText("Data Pengiriman Pulsa");

        data_pengiriman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Provider", "Jumlah Pulsa", "Harga", "Nomor Tujuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        data_pengiriman.setName(""); // NOI18N
        data_pengiriman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_pengirimanMouseClicked(evt);
            }
        });
        data_pengiriman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                data_pengirimanKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(data_pengiriman);
        if (data_pengiriman.getColumnModel().getColumnCount() > 0) {
            data_pengiriman.getColumnModel().getColumn(0).setResizable(false);
            data_pengiriman.getColumnModel().getColumn(1).setResizable(false);
            data_pengiriman.getColumnModel().getColumn(2).setResizable(false);
            data_pengiriman.getColumnModel().getColumn(3).setResizable(false);
            data_pengiriman.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("ID");

        form_id.setEditable(false);
        form_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_idActionPerformed(evt);
            }
        });

        jLabel2.setText("Provider");

        jLabel3.setText("Jumlah Pulsa");

        jLabel4.setText("Harga");

        form_harga.setEditable(false);
        form_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_hargaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nomor Tujuan");

        nomor_tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomor_tujuanActionPerformed(evt);
            }
        });

        button_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/edit.png"))); // NOI18N
        button_edit.setText("EDIT");
        button_edit.setToolTipText("");
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/delete.png"))); // NOI18N
        button_delete.setText("DELETE");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/insert.png"))); // NOI18N
        button_insert.setText("INSERT");
        button_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insertActionPerformed(evt);
            }
        });

        ComboBox_provider.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Telkomsel", "Indosat", "XL", "Axis", "Smartfren" }));
        ComboBox_provider.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_providerPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jumlah_pulsa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rp 5000", "Rp 10000", "Rp 25000", "Rp 50000", "Rp 100000" }));
        jumlah_pulsa.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jumlah_pulsaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        button_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/back.png"))); // NOI18N
        button_back.setText("BACK");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(form_id)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(form_harga)
                            .addComponent(nomor_tujuan)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox_provider, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlah_pulsa, 0, 152, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(data_pengiriman_pulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(244, 244, 244))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_back, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(button_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(button_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_insert)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(data_pengiriman_pulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(form_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_provider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah_pulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(form_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomor_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomor_tujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomor_tujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomor_tujuanActionPerformed

    private void form_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_idActionPerformed

    private void data_pengirimanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data_pengirimanKeyReleased
        
    }//GEN-LAST:event_data_pengirimanKeyReleased

    private void form_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_hargaActionPerformed
        
    }//GEN-LAST:event_form_hargaActionPerformed

    private void data_pengirimanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_pengirimanMouseClicked
        try{
            int row = data_pengiriman.getSelectedRow();
            String table_click = (data_pengiriman.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * from tbl_kirim where id='"+table_click+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if(rs.next()){
                String value1 = rs.getString("id");
                form_id.setText(value1);
                String value2 = rs.getString("provider");
                ComboBox_provider.setSelectedItem(value2);
                String value3 = rs.getString("jumlah_nominal");
                jumlah_pulsa.setSelectedItem(value3);
                String value4 = rs.getString("harga");
                form_harga.setText(value4);
                String value5 = rs.getString("nomor_tujuan");
                nomor_tujuan.setText(value5);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_data_pengirimanMouseClicked

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        if(form_id.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Tidak Bisa Menghapus Data :(");
        }else{
        int confirm = JOptionPane.showConfirmDialog(null,"Anda Yakin Ingin Menghapus Data?","Delete Data?",JOptionPane.YES_NO_OPTION);
        
        if(confirm == 0){
            String sql = "DELETE from  tbl_kirim where id=?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, form_id.getText());
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data!");
            pst.execute();
        }catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        update_table();
        }
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editActionPerformed
        try{
            if(form_id.getText().isEmpty() == true){
                JOptionPane.showMessageDialog(null, "Tidak Bisa Mengedit :(");
            }else{
            String val1 = form_id.getText();
            String val2 = ComboBox_provider.getSelectedItem().toString();
            String val3 = jumlah_pulsa.getSelectedItem().toString();
            String val4 = form_harga.getText();
            String val5 = nomor_tujuan.getText();
            
            String sql = "UPDATE tbl_kirim SET provider='"+val2+"',jumlah_nominal='"+val3+"',harga='"+val4+"',nomor_tujuan='"+val5+"' where id='"+val1+"'";
            pst = conn.prepareStatement(sql);
            form_id.setText(null);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Berhasil Meng-Edit !!");
            }
        }catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        update_table();
    }//GEN-LAST:event_button_editActionPerformed

    private void button_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insertActionPerformed
        try{
            if(nomor_tujuan.getText().isEmpty() == true && form_harga.getText().isEmpty() == true){
                JOptionPane.showMessageDialog(null, "Isi Nomor Tujuan!");
            }else{
            String sql = "INSERT into db_epulsa.tbl_kirim(id, provider, jumlah_nominal, harga, nomor_tujuan) VALUES(null,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, ComboBox_provider.getSelectedItem().toString());
            pst.setString(2, jumlah_pulsa.getSelectedItem().toString());
            pst.setString(3, form_harga.getText());
            pst.setString(4, nomor_tujuan.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Mengisi Data!");
            update_table();
            }
        }catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_button_insertActionPerformed

    private void ComboBox_providerPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_providerPopupMenuWillBecomeInvisible
        try{
        form_harga.setText(link.get(i).getharga());
        int x = ComboBox_provider.getSelectedIndex();
        int y = jumlah_pulsa.getSelectedIndex();
        //Kombinasi 2 jComboBox
        if (x==0 && y==0){
            i = 0;
            saldo = 5000;
            data();
        }
        else if (x==0 && y==1){
            i =1;
            saldo = 10000;
            data();
        }
        else if (x==0 && y==2){
            i =2;
            saldo = 25000;
            data();
        }
        else if (x==0 && y==3){
            i =3;
            saldo = 50000;
            data();
        }
        else if (x==0 && y==4){
            i =4;
            saldo = 100000;
            data();
        }
        else if (x==1 && y==0){
            i =5;
            saldo = 5000;
            data();
        }
        else if (x==1 && y==1){
            i =6;
            saldo = 10000;
            data();
        }
        else if (x==1 && y==2){
            i =7;
            saldo = 25000;
            data();
        }
        else if (x==1 && y==3){
            i =8;
            saldo = 50000;
            data();
        }
        else if (x==1 && y==4){
            i =9;
            saldo = 100000;
            data();
        }
        else if (x==2 && y==0){
            i =10;
            saldo = 5000;
            data();
        }
        else if (x==2 && y==1){
            i =11;
            saldo = 10000;
            data();
        }
        else if (x==2 && y==2){
            i =12;
            saldo = 25000;
            data();
        }
        else if (x==2 && y==3){
            i =13;
            saldo = 50000;
            data();
        }
        else if (x==2 && y==4){
            i =14;
            saldo = 100000;
            data();
        }
        else if (x==3 && y==0){
            i =15;
            saldo = 5000;
            data();
        }
        else if (x==3 && y==1){
            i =16;
            saldo = 10000;
            data();
        }
        else if (x==3 && y==2){
            i =17;
            saldo = 25000;
            data();
        }
        else if (x==3 && y==3){
            i =18;
            saldo = 50000;
            data();
        }
        else if (x==3 && y==4){
            i =19;
            saldo = 100000;
            data();
        }
        else if (x==4 && y==0){
            i =20;
            saldo = 5000;
            data();
        }
        else if (x==4 && y==1){
            i =21;
            saldo = 10000;
            data();
        }
        else if (x==4 && y==2){
            i =22;
            saldo = 25000;
            data();
        }
        else if (x==4 && y==3){
            i =23;
            saldo = 50000;
            data();
        }
        else if (x==4 && y==4){
            i =24;
            saldo = 100000;
            data();
        }
        else {
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan/Terjadi Kesalahan");
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_ComboBox_providerPopupMenuWillBecomeInvisible

    private void jumlah_pulsaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jumlah_pulsaPopupMenuWillBecomeInvisible
        try{
        form_harga.setText(link.get(i).getharga());
        int x = ComboBox_provider.getSelectedIndex();
        int y = jumlah_pulsa.getSelectedIndex();
        //Kombinasi 2 jComboBox
        if (x==0 && y==0){
            i = 0;
            saldo = 5000;
            data();
        }
        else if (x==0 && y==1){
            i =1;
            saldo = 10000;
            data();
        }
        else if (x==0 && y==2){
            i =2;
            saldo = 25000;
            data();
        }
        else if (x==0 && y==3){
            i =3;
            saldo = 50000;
            data();
        }
        else if (x==0 && y==4){
            i =4;
            saldo = 100000;
            data();
        }
        else if (x==1 && y==0){
            i =5;
            saldo = 5000;
            data();
        }
        else if (x==1 && y==1){
            i =6;
            saldo = 10000;
            data();
        }
        else if (x==1 && y==2){
            i =7;
            saldo = 25000;
            data();
        }
        else if (x==1 && y==3){
            i =8;
            saldo = 50000;
            data();
        }
        else if (x==1 && y==4){
            i =9;
            saldo = 100000;
            data();
        }
        else if (x==2 && y==0){
            i =10;
            saldo = 5000;
            data();
        }
        else if (x==2 && y==1){
            i =11;
            saldo = 10000;
            data();
        }
        else if (x==2 && y==2){
            i =12;
            saldo = 25000;
            data();
        }
        else if (x==2 && y==3){
            i =13;
            saldo = 50000;
            data();
        }
        else if (x==2 && y==4){
            i =14;
            saldo = 100000;
            data();
        }
        else if (x==3 && y==0){
            i =15;
            saldo = 5000;
            data();
        }
        else if (x==3 && y==1){
            i =16;
            saldo = 10000;
            data();
        }
        else if (x==3 && y==2){
            i =17;
            saldo = 25000;
            data();
        }
        else if (x==3 && y==3){
            i =18;
            saldo = 50000;
            data();
        }
        else if (x==3 && y==4){
            i =19;
            saldo = 100000;
            data();
        }
        else if (x==4 && y==0){
            i =20;
            saldo = 5000;
            data();
        }
        else if (x==4 && y==1){
            i =21;
            saldo = 10000;
            data();
        }
        else if (x==4 && y==2){
            i =22;
            saldo = 25000;
            data();
        }
        else if (x==4 && y==3){
            i =23;
            saldo = 50000;
            data();
        }
        else if (x==4 && y==4){
            i =24;
            saldo = 100000;
            data();
        }else {
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan/Terjadi Kesalahan");
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jumlah_pulsaPopupMenuWillBecomeInvisible

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run(){
            new PE_welcome().setVisible(true);
        }
    });
        this.dispose();
    }//GEN-LAST:event_button_backActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox_provider;
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_insert;
    private javax.swing.JTable data_pengiriman;
    private javax.swing.JLabel data_pengiriman_pulsa;
    private javax.swing.JTextField form_harga;
    private javax.swing.JTextField form_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jumlah_pulsa;
    private javax.swing.JTextField nomor_tujuan;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
