package PulsaElektronix;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 * @author Wiguna Ramadhan
 * @kelas X - RPL 2
 * @sekolah SMKN 1 CIBINONG
 */
public class PE_welcome extends javax.swing.JFrame {

    /**
     * Creates new form PKL_welcome
     */
    public PE_welcome() {
        initComponents();
        setIcon();
    }
public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        isi_pulsa = new javax.swing.JButton();
        history_pengiriman = new javax.swing.JButton();
        button_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pulsa Elektronix || Welcome !");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME!");

        isi_pulsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/isipulsa.png"))); // NOI18N
        isi_pulsa.setText("Isi Pulsa");
        isi_pulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_pulsaActionPerformed(evt);
            }
        });

        history_pengiriman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/data pulsa.png"))); // NOI18N
        history_pengiriman.setText("History Pengiriman");
        history_pengiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_pengirimanActionPerformed(evt);
            }
        });

        button_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PulsaElektronix/logout.png"))); // NOI18N
        button_logout.setText("LOGOUT");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(history_pengiriman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isi_pulsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(isi_pulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(history_pengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void history_pengirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_pengirimanActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
            new PE_dataPengiriman().setVisible(true);
        }
        });
        this.dispose();
    }//GEN-LAST:event_history_pengirimanActionPerformed

    private void isi_pulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_pulsaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
            new PE_isiPulsa().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_isi_pulsaActionPerformed

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Ingin Logout?","Confirmation!",JOptionPane.YES_NO_OPTION);
        if(confirm == 0){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
            JOptionPane.showMessageDialog(null, "Logout Success!");
            JOptionPane.showMessageDialog(null, "Terima Kasih :D");
            new PE_login().setVisible(true);
            }
        });
        this.dispose();
        }
    }//GEN-LAST:event_button_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_logout;
    private javax.swing.JButton history_pengiriman;
    private javax.swing.JButton isi_pulsa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
